-- DDL 1_4

--CRIA BANCO
CREATE DATABASE Exercicio_1_4;

--USA BANCO

USE Exercicio_1_4;

--CRIA TABELA

CREATE TABLE Usuarios
(
	IdUsuario INT PRIMARY KEY IDENTITY,
	Nome VARCHAR(20) NOT NULL,
	Email VARCHAR(20) NOT NULL UNIQUE,
	Senha VARCHAR(20) NOT NULL,
	Permissao VARCHAR(10) NOT NULL
)

CREATE TABLE Artistas
(
	IdArtista INT PRIMARY KEY IDENTITY,
	Nome VARCHAR(20) NOT NULL
)

CREATE TABLE Estilos
(
	IdEstilo INT PRIMARY KEY IDENTITY,
	Nome VARCHAR(20) NOT NULL
)

CREATE TABLE Albuns
(
	IdAlbum INT PRIMARY KEY IDENTITY,
	IdArtista INT FOREIGN KEY REFERENCES Artistas(IdArtista),
	Titulo VARCHAR(20) NOT NULL,
	DataLancamento DATE NOT NULL,
	Localizacao VARCHAR(30) NOT NULL,
	QtdMinutos INT NOT NULL,
	Ativo VARCHAR(10) NOT NULL
)

CREATE TABLE AlbunsEstilos
(
	IdAlbum INT FOREIGN KEY REFERENCES Albuns(IdAlbum),
	IdEstilo INT FOREIGN KEY REFERENCES Estilos(IdEstilo)
)

SELECT * FROM Estilos